import { createSlice } from "@reduxjs/toolkit";
// Define the initial state
const initialState = {
 user: null,
  token: null,
};

// Create the auth slice
const authSlice = createSlice({
  name: "auth",
  initialState,
  reducers: {
    setCredentials: (state, action) => {
      const { user, token } = action.payload;
 
      state.user = user;
      state.token = token;
    },
    logout: (state) => {
     
      state.user = null;
      state.token = null;
    },
    // Reducer to update user information
    updateUser: (state, action) => {
      const { user } = action.payload;
      if (user !== undefined) state.user = user;
   
    },
  },
});

// Export the actions generated by createSlice
export const { setCredentials, logout, updateUser } = authSlice.actions;

// Export the reducer to be used in the store
export default authSlice.reducer;

export const selectCurrentUser = (state) => state.auth.user;
export const selectCurrentToken = (state) => state.auth.token;

